### ISSUE TITLE
Potential improvement

### ISSUE THREAD

**Issue by sukus21** [ExFabian/EEU-File-Storage#1]
I just had a brain blast. You can store 2 extra bits per block if you use view and edit zones!

If you want to go even further than that, I don't know if the game limits how many zones you can have per world... So in theory, you could create 256 edit zones and 256 view zones, and get a whole 2 bytes extra per block!

**Comment by ExFabian** [comment]
I have thought of another way before of storing a bit more data per block by using a combination of sign colors, sign orientations and backgrounds, all of which are enough to store 1 more byte, maybe 1.5 per block. However, even with trying to implement both of these techniques, I'll be able to store 3 more bytes per block, which is just a 3% increase in potential size, doesn't seem that worth it.
